name: pipecapacity
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pip
  - pip:
    - plotly
    - dash
    - pyyaml
    - bumpver
    - webcolors
    - deepdiff
    - pytest
